### ISSUE TITLE
Why is composer installation unsupported?

### ISSUE THREAD

**Issue by sagikazarmark** [eltrino/DiamanteOroCRMIntegrationBundle#2]
I think in many cases people actually develop applications with Oro CRM. In that case, installation through composer might be a MUST.

Is it really unsupported or just require extra steps to make it work?

**Comment by odi-um** [comment]
Hi Márk,

Oro Package Manager installs everything through Composer + executes additional install or update scripts. Extension is available on packagist.org. Nobody restricts you from installing extension using Composer and then manually do steps from install script. You can find install script in root of the bundle.

Hope this helps you.

**Comment by sagikazarmark** [comment]
Hi Dmytro,

Thanks for the quick answer, it's absolutely helpful. Just to be sure: we are talking about index.php, right?

As I can see it does the following:
- Creates the attachments directory
- Creates a logo directory
- Executes a few commands
- Adds a few security records

Am I right?

About the attachments directory: it can be configured to be outside of the app directory (and it very likely will be with the new SensioDistributionBundle and Symfony version, reference: orocrm/platform#341), so hardcoding it to app/attachments might not be a good idea. What do you think?

**Comment by odi-um** [comment]
yes, you are correct. thats what it does.

Regarding attachments directory, you are right. In case new SensioDistributionBundle will be added, our hardcode will be ridiculous. We will monitor that pull request and will do required changes as soon as it will be accepted.

**Comment by sagikazarmark** [comment]
> yes, you are correct. thats what it does.

Thanks for confirmation.

> In case new SensioDistributionBundle will be added

Merging that PR only means that there can be a var directory which would be the correct place for attachments. However attachment directory path is already configurable I think.

Should I open a separate issue for this one?

**Comment by odi-um** [comment]
Yes, but it will be better to have it in eltrino/diamantedesk-application. Thanks.
